### ISSUE TITLE
Dutch (Nederlands) Translation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [puddletag/puddletag#172]
```
Have been working on a translation to Dutch. Hope you could include in soon.
```

Original issue reported on code.google.com by `fabian9b...@gmail.com` on 22 Mar 2012 at 5:07

Attachments:
- [puddletag_nl-nl.ts](https://storage.googleapis.com/google-code-attachments/puddletag/issue-172/comment-0/puddletag_nl-nl.ts)

**Comment by sandrotosi** [comment]
fixed via #264
