### ISSUE TITLE
Portuguese (Brazil) Translation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [puddletag/puddletag#190]
```
Generated 611 translation(s) (611 finished and 0 unfinished)
Ignored 25 untranslated source text(s)
```

Original issue reported on code.google.com by `Concentr...@gmail.com` on 27 Aug 2012 at 7:51

Attachments:
- [puddletag_pt_BR.ts](https://storage.googleapis.com/google-code-attachments/puddletag/issue-190/comment-0/puddletag_pt_BR.ts)

**Comment by sandrotosi** [comment]
fixed via #264
