### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [puddletag/puddletag#191]
```
Generated 634 translation(s) (633 finished and 1 unfinished)
Ignored 5 untranslated source text(s)

```

Original issue reported on code.google.com by `Concentr...@gmail.com` on 27 Aug 2012 at 7:53

Attachments:
- [puddletag_de.ts](https://storage.googleapis.com/google-code-attachments/puddletag/issue-191/comment-0/puddletag_de.ts)

**Comment by sandrotosi** [comment]
fixed via #264
