### ISSUE TITLE
Support for dsf (DSD) files is missing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [puddletag/puddletag#211]
```
DSF files use the ID3 Tag properties.

http://en.wikipedia.org/wiki/Direct_Stream_Digital


```

Original issue reported on code.google.com by `perry...@gmail.com` on 26 Nov 2013 at 3:15

**Comment by audiomuze** [comment]
DSF tagging is already implemented.  This feature request should be closed.

**Comment by sandrotosi** [comment]
thanks for checking, closing
