### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by keithgg** [puddletag/puddletag#300]
puddletag runs fine on current systems (and probably will until 2020ish). Porting to Python 3 would be at least a couple weeks worth of work. I don't have that time available. If I did I'd spend it on fixing bugs and adding features.

I'd be very happy to accept any contributions (code, not money) towards this goal though :-)

**Comment by chincheta0815** [comment]
Could you please comment on issue #316

**Comment by bernd-wechner** [comment]
A worthwhile endeavour. A week's work is pricey and I can't afford it. But I have puddletag set up on my dev box, with PyDev and will see what, if anything I ever find time for. In the meantime I'd be curious to know what IDE and/or dev tools you use for working on puddletag.

**Comment by keithgg** [comment]
Heh. Just re-read the sentence and saw it could be misinterpreted as me asking for donations. Code, not money is what I need.

I use emacs, but it really doesn't matter which IDE you use (just don't commit anything IDE specific).

**Comment by bernd-wechner** [comment]
Oh, I didn't mean it as money. I did in the sense that time is a currency of sorts too, I have only so much in my account to spend ;-).

**Comment by keithgg** [comment]
Work started in th py3 branch. https://github.com/keithgg/puddletag/tree/py3. Still a lot to be done, but at least you can load a folder. 

For the lurkers, please don't try to run it. It's not usable at all.

**Comment by TomBugnon** [comment]
This issue is referenced by #318 for all follow up about OSX support for puddletag. Is there by chance any progress on that respect? Thanks

**Comment by sandrotosi** [comment]
is there any update to this effort? Debian plan to drop python 2 with the next stable release (2 years away, more or less), and since puddletag is python2-onlu there's a chance we'd may not include it, which would be a shame -- thanks!

**Comment by DeathTBO** [comment]
Fedora 32 has dropped Python 2 support.

>(and probably will until 2020ish)

The future is now, and now it doesn't work :P

**Comment by rharmonson** [comment]
One of several applications dropped by Ubuntu 20.04 dropped due to the applications being based on python2.

Alternative until a python3 puddletag is release is picard.

**Comment by sandrotosi** [comment]
please check #468

**Comment by sandrotosi** [comment]
2.0.1 has been released, which is a port to python3 and pyqt5
