### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by mbirth** [puddletag/puddletag#361]
For some reason, puddletag crashes for me right after showing the splash and the main window:

```
$ puddletag
puddletag Version: 1.2.0
Locale: en_US
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

This is on Ubuntu 17.04 with all packages up to date. Is there any way to get a more detailed log?

**Comment by keithgg** [comment]
There's a function that could be causing the issue, but it's not used anymore. Are you running puddletag on a clean install (try deleting ~/.config/puddletag ~/.local/share/puddletag)?

**Comment by mbirth** [comment]
With both config directories renamed, it starts and shows the tree collapsed at `/`. As soon as I try to expand the root dir, it crashes again.

**Comment by keithgg** [comment]
Wit the same error?

**Comment by mbirth** [comment]
Looks like it:

```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
fish: “puddletag -d” terminated by signal SIGABRT (Abort)
```

(Last line is from fish shell.)

**Comment by keithgg** [comment]
Distro? DE? PyQt version? Puddletag from the repo or distro supplied?

**Comment by mbirth** [comment]
Ubuntu 17.04 Zesty (with Unity)
Puddletag is 1.2.0-2~webupd8~yakkety0 from [this PPA](http://www.webupd8.org/2011/01/puddletag-audio-tag-editor-gets-ubuntu.html)
PyQt is `4.11.4+dfsg-2` from official Ubuntu repos.
(PyQt5 is also installed, but it seems puddletag uses Qt4.)

With puddletag `1.2.0-1` from the Ubuntu repos it's the same problem.

**Comment by mbirth** [comment]
I seem to have found the culprit: The latest Keybase client (https://keybase.io/) creates a directory `/keybase` and mounts something there via FUSE. And it seems that's what confuses puddletag. Once I unmount that directory, puddletag works again.

However, still looks like some sort of bug since no other program has problems with that mount.

**Comment by sandrotosi** [comment]
not sure there's any work we need to do here; closing
