### ISSUE TITLE
Amazon Tag Source Error 400: Bad Request

### ISSUE THREAD

**Issue by jtwang83** [puddletag/puddletag#363]
Searching Amazon in the Tag Sources pane always gives "HTTP Error 400: Bad Request"

No error is printed on stdout or stderr.

I am using release v1.2.0

**Comment by keithgg** [comment]
Looks like my amazon account got banned without notice. Will try and find a workaround some time soon.

**Comment by mhham** [comment]
FYI, [same thing](https://forums.mp3tag.de/index.php?s=&showtopic=22597&view=findpost&p=96810) happened for mp3tag editor

**Comment by keithgg** [comment]
thanks @mhham. Looks like just creating a new account will be an issue.

For now users should create their own associates account [don't ask me how, the amazon website is a maze I don't care to navigate] and plug the details into the Tag Source's settings.

**Comment by paxunix** [comment]
I have a PR for those of us who have an associates account and want to use it.  If you do, it works great with a couple minor changes.  I don't see any other way to resolve this except significant modifications to how the amazon tagsource works (like screen scraping a search results page and following detail page links).

**Comment by sandrotosi** [comment]
we're going to look at this with #629
