### ISSUE TITLE
Qt 4 removal in Debian testing (Buster)/unstable

### ISSUE THREAD

**Issue by ghost** [puddletag/puddletag#380]
https://lists.debian.org/debian-devel-announce/2017/08/msg00006.html

**Comment by billie80** [comment]
The same goes for Gentoo [1]. If there is no port to QT5 or equivalent puddletag will be removed from the distribution soon.

[1] https://bugs.gentoo.org/631788

**Comment by wimstefan** [comment]
Any news on that?
Gentoo definitely will remove puddletag in the beginning of July and I honestly have to say I'm lost then :-/

**Comment by SammysHP** [comment]
Qt4 was removed in Arch Linux as well.

**Comment by DolphinStKom** [comment]
Qt 4 and puddletag removal in Gentoo too(((

**Comment by sandrotosi** [comment]
We recently released 2.0.1 which contains the ports to python3 and pyqt5
