### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by whyman** [puddletag/puddletag#384]
Looks like there is lots of good stuff in master, do you plan on cutting a new release soon?

**Comment by DolphinStKom** [comment]
need new version for qt5

**Comment by sandrotosi** [comment]
We recently released 2.0.1 which contains the ports to python3 and pyqt5

**Comment by DolphinStKom** [comment]
thank you so much! I will upload the fixed ebuild to the overlay for the gentoo later

**Comment by sandrotosi** [comment]
thanks @DolphinStKom ! if you can give us back a URL we can refer to for the Gentoo package, we're gonna start collecting them and publish on the frontpage

**Comment by DolphinStKom** [comment]
@sandrotosi yes of course, I'll let you know when I upload it

**Comment by DolphinStKom** [comment]
@sandrotosi ready

**overlay:**
[](https://github.com/istitov/stuff)

**for install:**
sudo layman -a stuff
sudo emerge -av puddletag

**Comment by sandrotosi** [comment]
Thanks!
