### ISSUE TITLE
Autonumbering gives keyerror

### ISSUE THREAD

**Issue by aldeano** [puddletag/puddletag#391]
When I run autonumbering on a folder with one album, the first track gets processed, but it stops with the second track. Python error:
`Traceback (most recent call last):`
`  File "/usr/lib/python2.7/site-packages/puddlestuff/puddletag.py", line 775, in writeTags
    ret = self._write(tagiter, rows, previews)`
  `File "/usr/lib/python2.7/site-packages/puddlestuff/puddletag.py", line 734, in _write
    [setRowData(row, f, undo=True) for row, f in izip(rows, tagiter)]`
 ` File "/usr/lib/python2.7/site-packages/puddlestuff/mainwin/funcs.py", line 416, in tagiter
    val = function(rowtags.get(field, u''), rowtags, state, r_tags=f)`
  `File "/usr/lib/python2.7/site-packages/puddlestuff/findfunc.py", line 844, in runFunction
    return func(**topass)`
 `File "/usr/lib/python2.7/site-packages/puddlestuff/functions.py", line 98, in autonumbering
    tracknum = state['autonumbering'][index]`
`KeyError: 2
`
Using puddletag 1.2.0-1 in archlinux up to date.

**Comment by dglava** [comment]
That's strange, because I just tested it on Arch Linux with the same version and I don't get that error.
