### ISSUE TITLE
Website header double height when zoomed in

### ISSUE THREAD

**Issue by mxmilkiib** [puddletag/puddletag#395]
The search bar pops down on to a new line when zoomed in (1280x1024 (minus i3 container borders)). Upping the container width to the below slightly fixes this for 110% and 125% level of zoom.

```
@media (min-width: 992px)
.container {
    width: 1075px;
}
```

**Comment by sandrotosi** [comment]
i dont think it's like that anymore; closing

**Comment by mxmilkiib** [comment]
I'm afraid it is;

![image](https://user-images.githubusercontent.com/108225/97601360-fdc88b00-1a01-11eb-96d0-e28aca8c1ede.png)
