### ISSUE TITLE
Remove "delete without confirmation" option

### ISSUE THREAD

**Issue by seanidzenga** [puddletag/puddletag#399]
Having a massively destructive option available and ready to be misclicked could cause much more harm than good, I'd even be so bold as to argue that tagging and management software shouldn't be capable of destructive operations like that at all but least of all ones that have no method of being rolled back and have no confirmation dialog.

Perhaps a better solution would be to use the already-existing delete option but when the first dialog appears have the option to "never show me this again".

(Obviously this is mostly motivated by my own clumsiness as I just lost an album to this operation that I must now re-rip)

**Comment by sandrotosi** [comment]
this is a duplicate/variant of #223, i'm going to close this issue and maintain the other one (as it was submitted earlier) and implement a "delete to trash" functionality as part of fixing it

**Comment by absolutelynothinghere** [comment]
It's been 5 years and this is still an issue. How hard is it to remove a destructive menu option until an alternative is developed?

@sandrotosi

**Comment by sandrotosi** [comment]
@absolutelynothinghere open a PR or you should refrain from using a confrontational tone. we are providing a tool for everyone to use and contribute, and we own you nothing more.
