### ISSUE TITLE
AppImaging puddletag

### ISSUE THREAD

**Issue by ghost** [puddletag/puddletag#408]
as stated here https://github.com/keithgg/puddletag/issues/300 and here https://github.com/keithgg/puddletag/issues/313 it seems that porting puddletag in qt5 and py3 is proceding slowly... meanwhile many distributions plan to drop qt4 support https://github.com/keithgg/puddletag/issues/380 ... i think that an AppImaged version of puddletag could temporary solve this incombent problem until the porting is completed... please consider to release an AppImage version of puddletag 

https://appimage.org/

**Comment by farshee90** [comment]
as stated here https://github.com/keithgg/puddletag/issues/288 it seems that https://github.com/probonopd has packaged puddletag in AppImage format... i will try to contact him to ask him if he's available for mantaining puddletag AppImage updated

**Comment by DolphinStKom** [comment]
need qt5 version, gentoo closed support for puddletag(

**Comment by probonopd** [comment]
If you build an AppImage which bundles Python and Qt4 or Qt5 then it should run just fine.

Check out [Ultimaker Cura for Linux](https://github.com/Ultimaker/Cura/releases), they have been doing exactly that for quite a while now with their PyQt based application.

Please let me know if you are running into any issues.

**Comment by sandrotosi** [comment]
-1 on appimages

We recently released 2.0.1 which contains the ports to python3 and pyqt5, please use that (or ask you distribution to update the package)

**Comment by Samueru-sama** [comment]
Can we please have an appimage of puddletag? Right now the aur pacakge has been broken for 2 weeks and the pr fixing the issue has also been open for that long as well...

**Comment by sandrotosi** [comment]
the way to install puddletag are listed [here](https://github.com/puddletag/puddletag?tab=readme-ov-file#how-to-install), every other mechanism is community-provided and we do not support/maintain it.

im locking this discussion to prevent further comments.
