### ISSUE TITLE
Bitrate showing as 0kb/s on Mint 18.3. Works on Mint 19

### ISSUE THREAD

**Issue by ranperry** [puddletag/puddletag#417]
Running the latest version (1.2.0) on Mint 18.3, any FLAC file is shown with 0kb/s under the bitrate column. Using Mint 19 with the same Puddletag version, any FLAC file (16bit / 24Bit) is shown properly.

Any ideas?

**Comment by sandrotosi** [comment]
i imagine the new version of mint has some dependency packages at a newer version than 18.3.

please re-open if this still applies with puddletag/2.0.1 on an up-to-date Mint
