### ISSUE TITLE
Current Status, etc.

### ISSUE THREAD

**Issue by keithgg** [puddletag/puddletag#418]
Hi there. It's been a while.

The project has been in stasis now for a bit and I've lacked not just the time, but the motivation to do anything with it. Ever since streaming became useful enough, I haven't needed puddletag much on the daily and what it does is more than enough for my uses.

So the plan for puddletag is that I'll be sunsetting it unless more able bodies volunteer. Marko Hauptvogel has been kind enough to contribute change for PyQt5 [`git checkout pyqt5`]. Unless someone else jumps in, I'll do the Python3 migration somewhere in January 2018 [holding thumbs], after which I'll halt development and only do bugfixes where needed [promise to look at the current open tickets as well].

Suggestions and feedback are welcome.

**Comment by ranperry** [comment]
Please reconsider. EasyTag and Qoobar are not maintained anymore. There is still a demand for quality taggers. mp3tag, tag scanner, etc... are updated monthly (on Windows). People still need to use this tool.

Thanks!

**Comment by murlakatamenka** [comment]
> Unless someone else jumps in, I'll do the Python3 migration somewhere in January 2018 [holding thumbs]

You mean January **2019**, right?

Anyway after the project migrates to Python 3 (PyQt 5 is also very welcome, for sure) I'm willing to take care of it, i.e. to become its maintainer.

I can help with Python 2 ->  3 migration too (to get more familiar with the codebase at the very least) but I'm not a Python 2 guy so I'd prefer to have some guidance, at least initial. We can probably do it together, @keithgg ? Let me know what you think, please.

**Comment by AwesamLinux** [comment]
While some may have switched to Streaming, a lot of people especially audiophiles still want to have a local music library in best possible audio quality.

Personally, I use this tool also for tagging videos that are in MP4 containers. it is really useful with software like Jriver Media Center that can read those tags. In MP3tag it is now possible to tag MKA and MKV files too, and that is something that I would have liked to see in puddletag.

I guess my point is that there is still need for tagging tools, not only for music but also for videos.

**Comment by keithgg** [comment]
Minor status update. The migration has started. Still a ways to go, but making progress. If all goes well and I still have time, there should be a preview in mid Feb.

@murlakatamenka yeah I meant Jan 2019. Do you have experience with Python at all?

I'll mostly need help with getting past the initial hurdles, ie. triaging bugs that arise from the migration.

**Comment by murlakatamenka** [comment]
@keithgg yeah, I do have Python experience.
Let me make a short introduction.

- Arch Linux + KDE user, so Qt5 controls pretty much everywhere. Rarely, but I still boot into Windows.
- I've been using mp3tag for 5+ years at least.
- VGMDB contributor since [2013](https://vgmdb.net/db/user.php?do=submissions&id=13736&filter=albums&start=175) (tracklists were imported mostly from mp3tag).
- Technical background is from C++. I've been occasionally writing minor personal stuff in Python 3 over a few years already. List/dict comprehension, generators, decorators, lambdas etc won't confuse me.

I didn't work closely with large Python codebases but that's fine for me. VS Code and PyCharm Community Edition are the tools I use, nothing new here, I guess.

> I'll mostly need help with getting past the initial hurdles, ie. triaging bugs that arise from the migration.

I can help with it although my knowledge about difference of Python 3 vs 2 is like this: Unicode support, `//` (integer division) and `print()`.

**Comment by mistersister** [comment]
any update on the status of this wonderful and irreplaceable application?

**Comment by userx-bw** [comment]
yes my distro dropped support for it due to it being out dated, I can no longer use it in my distro as a result, and there is no replacement that even comes close to this one.

**Comment by keithgg** [comment]
Hey all

Current status is that I just can't find the time to dedicate to the project. Any contributors are welcome.

@murlakatamenka I've given you commit access. If anyone else wants to contribute, let me know.

**Comment by murlakatamenka** [comment]
@keithgg yup, I see it, thanks.
I'll be looking through the issues so far, will be able to work more closely after June 23rd.

What can you say about the current status of migration to python 3 / PyQt5?

**Comment by keithgg** [comment]
Sounds great!

There's a py3 and python3 branch. python3 is more recent. I think I got the GUI up, but there were still lots of issues to sort with the PyQt5 slots mechanism changing.

**Comment by Arnvidr** [comment]
Any updates on this? I tried to go looking for the python3 branch, to see if there was anything I could help with, but there's no trace of any such branch?

**Comment by sandrotosi** [comment]
@keithgg just to let you know that puddletag has been removed from Debian because it still depends on Qt5, maybe it's time to accelerate the release of a python3 + Qt5 version?

**Comment by thefoster** [comment]
I'd really like to see puddletag running on focal fossa, as i can't upgrade my audio workstation (bionic) until then.
I remember how happy i was when puddletag has been released thus first prividing a usable tag editor on linux for effective mass tagging.
To me, there's no point using one of the other taggers available for Linux.
Unfortunately, i don't have sufficient skills in neither Qt nor Python programming to solve this problem myself. 
Hope there will be someone with a solution.

**Comment by sandrotosi** [comment]
@thefoster you can try https://github.com/sandrotosi/puddletag , where we're working to port puddletag to PyQt5 and Python3; if you find an issue, just open an issue on that project

**Comment by sandrotosi** [comment]
I think this ticket has been taken care of:

- port to python3 and pyqt5 has been completed and released as of version 2.0.1
- we know have an org on github, where development continues
- we added more people interested in contributing to puddletag and we are building up again a community of developers
- debian packaging has resumed and 2.0.1 has been uploaded (not available to end users yet)

if other items are still pending/feature missing, please log new issues

**Comment by bernd-wechner** [comment]
That is awesome. If a `.deb` is built and has been uploaded to the Debian repo, couldit be made available as a download here on the github repo in the interim. It can take quite some time for `.debs` to find their way to Debian, then Ubuntu and downstream (Mint) repos of course and often packages that have a vibrant dev community (and great to see Puddletag has one again) offer a direct `.deb` download or a PPA.

**Comment by sandrotosi** [comment]
for now, i would prefer to wait and have an official package from debian; if the wait becomes too long, we'll re-evaluate then
