### ISSUE TITLE
I give up on basic operation: how to delete a tag?

### ISSUE THREAD

**Issue by OnkelTem** [puddletag/puddletag#420]
Despite it looks powerfull, I couldn't perform even basic operations like assigning value to tags.
To the left I see the Tag Panel and since it allows user input I reasoned that it can be used for tags modification. It's obvious.

So the the right I selected a file then assigned some value for a tag... and then what? I didn't see any **OK** or **Apply** button. Maybe it's autosubmitted I thought? To check I selected another file in the list and blah.. my information has disappeared. So it didn't work for no apparent reason.

Then I tried to clear some tag. Using the same approach as above I didn't manage to achieve that, but then I discovered "The combo" field and tried to make some use of it. I played with masks until I realised how they work and finally I got it working, in both ends. But yet it didn't help me neither to update tags nor to clear those values - and that even when I was setting values to **<blank>**.

I read tutorials, walked through documentation, searched forums and finally found something: I built some red dragons using Actions and Functions to change just a silly value. But to enter some other value I have to change my action. Is there some direct way of doing things? Is there any use of the **Tag Panel** to the left or it's there to distract and break hopes?

**Comment by OnkelTem** [comment]
Hello?

**Comment by ranperry** [comment]
You need to save your changes. Click on the save icon or use ctrl+s.

**Comment by OnkelTem** [comment]
Omg. Really? Then why this button is not in the Tag Panel?
