### ISSUE TITLE
branch pyqt5 problems

### ISSUE THREAD

**Issue by DolphinStKom** [puddletag/puddletag#425]
Hi! To begin, I would like to tell the author of the application and to those who helped him thank you so much! This is a very cool application and I am glad that after years there is at least some activity in the development of the application, thanks!

get down to business, have same problem... installed application from branch pyqt5, system gentoo. have crashed when I select directory(worked only drag and drop), 

```
puddletag Version: 1.2.0
qt5ct: using qt5ct plugin
Locale: ru_RU
qt5ct: D-Bus global menu: no
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/puddlestuff/puddletag.py", line 558, in openDir
    filename = filename[0]
TypeError: 'bool' object has no attribute '__getitem__'
Аварийный останов
```

dev-lang/python-2.7.15
dev-python/PyQt5-5.12_pre1812231618

and I cant chose edit tags for any files (invisible in all menu).
I attach my ebuild and screen with inactive buttons.
[puddletag-9999.ebuild.txt](https://github.com/keithgg/puddletag/files/2751426/puddletag-9999.ebuild.txt)
![2019-01-12 01-26-30](https://user-images.githubusercontent.com/4992884/51064618-459dd880-1609-11e9-8ad0-94e414b9702f.png)

**Comment by DolphinStKom** [comment]
Thanks for the answer, after the update, the choice of the directory was repaired ... but the extended tags and operations with tags are still not available
![photo_2019-01-26_14-33-35](https://user-images.githubusercontent.com/4992884/51787198-89e7b780-2177-11e9-96e1-2326284e0f73.jpg)

**Comment by fabastrid** [comment]
yes, all the features are greyed out, no chance do to anything

**Comment by cmorgenstern** [comment]
This issue is still present in the [Qt5 build for Arch Linux](https://aur.archlinux.org/packages/puddletag-qt5-git/). Most features are greyed out and not available. Does this just represent the current state of the Qt5 branch, or is this a bug?

**Comment by sandrotosi** [comment]
@keithgg just to let you know that puddletag has been removed from Debian because it still depends on Qt5, maybe it's time to accelerate the release of a python3 + Qt5 release?
