### ISSUE TITLE
Installation aborted

### ISSUE THREAD

**Issue by coevolving** [puddletag/puddletag#432]
puddletag-git seems to install from AUR fine, but then doesn't work. Starting from command line:

[~]$ puddletag 
puddletag Version: 1.2.0 Locale: en_CA 
Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/puddlestuff/mainwin/dirview.py", line 278, in selectionChanged if self._lastselection: AttributeError: 'DirView' object has no attribute '_lastselection' 
Aborted (core dumped)

[~]$ lsb_release -rd 
Description: Manjaro Linux 
Release: 18.0.3

[~]$ plasmashell --version 
plasmashell 5.15.0

[~]$ kf5-config --version 
Qt: 5.12.1 
KDE Frameworks: 5.55.0 
kf5-config: 1.0 

I've reported this experience at https://aur.archlinux.org/packages/puddletag-git .

**Comment by cmorgenstern** [comment]
Experiencing the same issue - pyqt5 branch build:
```
[user@host ~]$ puddletag
puddletag Version: 1.2.0
qt5ct: using qt5ct plugin
Locale: en_US
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/puddlestuff/mainwin/dirview.py", line 278, in selectionChanged
    if self._lastselection:
AttributeError: 'DirView' object has no attribute '_lastselection'
Aborted (core dumped)`
```
As the maintainer of the puddletag-git Arch User Repository (AUR) package is not actively maintaining it anymore, I wrote my own [PKGBUILD](https://gist.github.com/cmorgenstern/663c6ae9dee33216e24ca6ea7b3c5ad6).

I also briefly experienced the same issue reported [here](https://github.com/keithgg/puddletag/issues/435) before working around it (see my comment). 

Any assistance would be great - I would really like to get a qt5 puddletag working. Thanks!

**Comment by cmorgenstern** [comment]
Arch Linux has moved the qt4 framework into the AUR, so getting puddletag successfully working on Qt5 would be great. I have also taken over maintaining the puddletag-git package in the AUR - any guidance you could provide in getting Qt5 puddletag working successfully would be much appreciated, as the puddletag-git AUR package is failing to run currently due to the AttributeError reported above.

**Comment by cmorgenstern** [comment]
The PKGBUILD was missing a dependency qt5-svg - seems to be building and running successfully now.

**Comment by sandrotosi** [comment]
Puddletag is available again in Arch: https://aur.archlinux.org/packages/puddletag/
