### ISSUE TITLE
Discogs tagging doesn't work

### ISSUE THREAD

**Issue by donlombardo** [puddletag/puddletag#439]
I'm getting this error message today, when I try to fetch tags from Discogs:

An error occurred: HTTP Error 308: Permanent Redirect

No album works.

**Comment by jaanpehechaanho** [comment]
same problem here :/

**Comment by frei-style** [comment]
I submitted the pull request  #441 to fix this.

To fix this manually, change the discogs.py on your system. This is an example of a puddletag installation on Xubuntu 19.04.

`sudo vim /usr/lib/python2.7/dist-packages/puddlestuff/tagsources/discogs.py
`

Search for the variables SITE_MASTER_URL, SITE_RELEASE_URL, API_RELEASE_URL, API_MASTER_URL, SITE_URL, BASE_URL and replace the http with https.

The variables should now look like this:

> SITE_MASTER_URL = 'https://www.discogs.com/master/'
> SITE_RELEASE_URL = 'https://www.discogs.com/releases/'
> API_RELEASE_URL = 'https://api.discogs.com/releases/'
> API_MASTER_URL = 'https://api.discogs.com/masters/'
> SITE_URL = 'https://www.discogs.com'
> 
> BASE_URL = 'https://api.discogs.com/%s'

Save the file and restart puddletag.

**Comment by jaanpehechaanho** [comment]
thank you so much. this worked.

**Comment by sandrotosi** [comment]
fixed via #441
