### ISSUE TITLE
puddletag cannot convert unicode chars

### ISSUE THREAD

**Issue by sigzegv** [puddletag/puddletag#444]
If songs contain special accented characters, puddletag just crashes with this error : 
```
puddletag Version: 1.2.0
Locale: fr_FR
TypeError: invalid result from TagModel.data(), unable to convert a Python 'unicode' object to a C++ 'QString' instance
Abandon (core dumped)
```

**Comment by sandrotosi** [comment]
We recently released 2.0.1 which contains the ports to python3 and pyqt5; python3 is unicod-only so this bug should be fixed (reopen if it's not)
