### ISSUE TITLE
Python 3 Plans?

### ISSUE THREAD

**Issue by terjeros** [puddletag/puddletag#451]
Linux distros are starting to remove Python 2 support due to end of life: https://pythonclock.org/

Any Python 3 plans in near future?

**Comment by RafaelLinux** [comment]
I agree, or at least create an AppImage to avoid this dependency of Python version

Thank you

**Comment by Pastim** [comment]
An appimage solution has been found. See #464

**Comment by sandrotosi** [comment]
please have a look at #468

**Comment by sandrotosi** [comment]
We recently released 2.0.1 which contains the ports to python3 and pyqt5
