### ISSUE TITLE
Arch build problems with mutagen, with fix

### ISSUE THREAD

**Issue by petef4** [puddletag/puddletag#453]
puddletag-git from AUR was blocking pacman updates of my system.

    error: failed to prepare transaction (could not satisfy dependencies)
    :: installing python2-mutagen (1.43.0-1) breaks dependency 'mutagen' required by puddletag-git

That is because mutagen 1.43.0 removed plain 'mutagen' from its provides.

I fixed the problem by changing 'mutagen' to 'python2-mutagen' in each of PKGBUILD and .SRCINFO. (I also incremented their pkgrel to 2.)

**Comment by petef4** [comment]
Here is some history of mutagen.

1.42.0-1 2019-02-06 renamed mutagen to python2-mutagen but still provided mutagen as a transition.

1.43.0-1 2019-11-18 removed mutagen, only python2-mutagen is provided.

Mutagen is a split package providing python2-mutagen and python3-mutagen. 1.43.x may be the last to support Python 2.

**Comment by sandrotosi** [comment]
there's a new package for puddletag on arch: https://aur.archlinux.org/packages/puddletag/
