### ISSUE TITLE
Puddletag on Kali Linux ???

### ISSUE THREAD

**Issue by RimazFlyil** [puddletag/puddletag#455]
i have followed the instruction http://docs.puddletag.net/download.html and installed on my kali .
i have used python setup.py istall . its showing in my application list but when i click i am getting this error message?
"Error: The configobj module wasn't found. Please check that it's installed properly. Download it from your distro's repository (usually python-configobj) or directly from http://code.google.com/p/configobj/ "

how can make it work . or if not how can i remove puddletag.

thanks

**Comment by sandrotosi** [comment]
the latest release has been uploaded to Debian, once it's accepted it will transition to Kali (or you can ask to be synced, not sure how it works) but in the meantime you can install puddletag from source following https://github.com/puddletag/puddletag#3-prerequisites + https://github.com/puddletag/puddletag#4-installation
