### ISSUE TITLE
PyQt5 & Python 3 branch started

### ISSUE THREAD

**Issue by sandrotosi** [puddletag/puddletag#468]
I saw a lot of people were unhappy about the removal of puddletag from many linux distros, so i took some time to merge the pyqt5 and py3 branches into https://github.com/sandrotosi/puddletag (the default branch is the one with the merge).

puddletag starts, and can do basic operations; there's still quite a lot to do, but let me know (either here or opening issues/prs in https://github.com/sandrotosi/puddletag) what you find and i'll try and address them as they come

to run:

```
git clone https://github.com/sandrotosi/puddletag
cd puddletag
apt-get install python3 python3-six python3-mutagen python3-configobj python3-pyparsing python3-pyqt5 python3-pyqt5.qtsvg
PYTHONPATH=source/ ./source/puddletag
```

**Comment by ranperry** [comment]
Excellent! Many thanks. Looking forward to test this over the weekend.

**Comment by ranperry** [comment]
Getting this error when trying to run puddletag:

ran@vbox:~/Code/puddletag/source$ ./puddletag
puddletag Version: 2.0.0
Locale: en_CA
Traceback (most recent call last):
  File "./puddletag", line 334, in <module>
    win = MainWin()
  File "/home/ran/Code/puddletag/source/puddlestuff/puddletag.py", line 331, in __init__
    menus = ls.get_menus('menu')
  File "/home/ran/Code/puddletag/source/puddlestuff/loadshortcuts.py", line 49, in get_menus
    menus = [(z, temp[z]) for z in settings[section + 'attrs']['order']]
KeyError: 'order'

**Comment by sandrotosi** [comment]
@ranperry mind opening an issue at https://github.com/sandrotosi/puddletag/issues ? thanks!

**Comment by kappclark** [comment]
Thanks for the reply --

I followed your instructions ... 

2 of the packages do not install:
Error: Unable to find a match: python3-pyqt5 python3-pyqt5.qtsvg

The puddletag runs ... but it does not show up in the context menu when I choose "Open With" by right-clicking o an MP3 the way I did before ... fwiw - I am running Mate in FC32

Bill Clark

**Comment by sandrotosi** [comment]
@kappclark please report issues at https://github.com/sandrotosi/puddletag/issues 

> 2 of the packages do not install:
> Error: Unable to find a match: python3-pyqt5 python3-pyqt5.qtsvg

what distro do you use? the commands are for debian-based distros, that are recent enough to have the right packages; you need to adapt those commands if you're on a different distro or upgrade to a more recent one if you're debian-based

**Comment by kappclark** [comment]
I am running Fedra 32 / MATE desktop .. I substituted DNF doe APT-GET -- like I said , everything installed except for those 2 packages ,,, here is what I can share: (host name is picard)

[billyboy@picard puddletag]$ sudo dnf install python3 python3-six python3-mutagen python3-configobj python3-pyparsing python3-pyqt5 python3-pyqt5.qtsvg
Last metadata expiration check: 0:29:59 ago on Sun 14 Jun 2020 03:26:37 PM EDT.
Package python3-3.8.3-1.fc32.x86_64 is already installed.
Package python3-six-1.14.0-2.fc32.noarch is already installed.
Package python3-mutagen-1.43.0-2.fc32.noarch is already installed.
Package python3-configobj-5.0.6-20.fc32.noarch is already installed.
Package python3-pyparsing-2.4.7-1.fc32.noarch is already installed.
No match for argument: python3-pyqt5
No match for argument: python3-pyqt5.qtsvg
Error: Unable to find a match: python3-pyqt5 python3-pyqt5.qtsvg
I hope this helps ... 



    On Sunday, June 14, 2020, 4:08:46 PM EDT, Sandro Tosi <notifications@github.com> wrote:  
 
 


@kappclark please report issues at https://github.com/sandrotosi/puddletag/issues


2 of the packages do not install:
Error: Unable to find a match: python3-pyqt5 python3-pyqt5.qtsvg


what distro do you use? the commands are for debian-based distros, that are recent enough to have the right packages; you need to adapt those commands if you're on a different distro or upgrade to a more recent one if you're debian-based

**Comment by sandrotosi** [comment]
it doesnt help; the readme clears says "The package names may be different in different distributions." so you need to find what's the right package names are for fedora, maybe python3-qt5, i dont use that distro.

**Comment by kappclark** [comment]
OK - will look further into the correct mame on the FC distro -- thanks for the reply...

    On Sunday, June 14, 2020, 5:43:05 PM EDT, Sandro Tosi <notifications@github.com> wrote:  
 
 


it doesnt help; the readme clears says "The package names may be different in different distributions." so you need to find what's the right package names are for fedora, maybe python3-qt5, i dont use that distro.

**Comment by sandrotosi** [comment]
@kappclark if you find out the right combination of packages, please file an issue at https://github.com/sandrotosi/puddletag/issues (as in a new issue, not replying to this one) so that we can update the instructions

**Comment by sandrotosi** [comment]
Puddletag 2.0.1 has been released, which is a port to python3 and pyqt5; it has also been released to Debian (but it's waiting in a queue to get accepted, since it's a new project)
