### ISSUE TITLE
Web sources: Tagging

### ISSUE THREAD

**Issue by GoogleCodeExporter** [puddletag/puddletag#47]
```
Implement additioonal web sources for tagging:
discogs
Amazon
Rateyourmusic
Last.FM
good old freedb...
```

Original issue reported on code.google.com by `forumsco...@gmail.com` on 6 Jan 2010 at 5:43

**Comment by sezanzeb** [comment]
I'd like to download covers from last.fm automatically. I don't think this is currently possible

**Comment by sandrotosi** [comment]
> I'd like to download album covers from last.fm. I don't think this is currently possible

we would happily review a PR implementing this
