### ISSUE TITLE
No package in Fedora 32

### ISSUE THREAD

**Issue by kappclark** [puddletag/puddletag#472]
Was running Puddletag in FC31, then the pkg is unavail in FC32. Python 2.x support is dropped in FC32 -- any pland to upgrade Puddletag ? Or is there a simple remedy for this ?? have been using MP3Tag in Wine since upgrade.

**Comment by sandrotosi** [comment]
@kappclark if you want to help out, please have a look at #468

**Comment by miniworm** [comment]
Solution for your problem is to use newly created AppImagge which will run on Fedora 32, Ubuntu 20.04 and any other new distro. Jut take a look at #464

**Comment by sandrotosi** [comment]
I wrote to the last maintainer in Fedora, to ask them if they're interested in resuming its maintenance. @kappclark you may want to follow up with fedora user support to get it prioritize (i'm no Fedora user)
