### ISSUE TITLE
Amazon lookup deprecated? Throws An error occured: Invalid Access or Secret Key

### ISSUE THREAD

**Issue by sandrotosi** [puddletag/puddletag#521]
<a href="https://github.com/audiomuze"><img src="https://avatars0.githubusercontent.com/u/6852511?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [audiomuze](https://github.com/audiomuze)**
_Tue Jun 30 16:43:55 2020_
_Originally opened as https://github.com/sandrotosi/puddletag/issues/45_

----

![image](https://user-images.githubusercontent.com/6852511/86153238-42e2bc00-baf9-11ea-85d5-4bf455cfd6fc.png)

**Comment by paul4ig** [comment]
Where do you go to create your own Amazon keys?

**Comment by sandrotosi** [comment]
this will be taken care of #629 -- currently Amazon tag source is non functional
