### ISSUE TITLE
QFileDialog in Native Dialog mode starts populated 

### ISSUE THREAD

**Issue by tonurics** [puddletag/puddletag#535]
Starting in 2.0.1: the Open or Addend Folder function shows a native dialog. In KDE/Plasma, that dialog is populated by the last used file URL [which actually takes about a second to animate and display]. Previously, the dialog shown was empty; which allowed the mouse free workflow: CTRL+O, CTRL+V [paste] and Enter to quickly switch folders.

A quick fix to restore the previous functionally:
https://github.com/puddletag/puddletag/blob/e0d35889d70507dfd0a8dc00cf7c8e5361deba0f/source/puddlestuff/puddletag.py#L451

To:
`translate("Main Window", 'Import directory...'), dirname, QFileDialog.ShowDirsOnly|QFileDialog.DontUseNativeDialog))`

It would be nice, if that was made the default option [or a toggle for it in the settings, or a dialog with just a folder URL entry].

FYI: I played around with QFileDialog Class, trying to get the native dialog to stop populating itself. But the native dialog doesn't appear to respect the QFileDialog options.

**Comment by sandrotosi** [comment]
hey @tonurics thanks for the report! it feels like you have a good grasp of the problem, would you mind submitting a PR for this? thanks!

**Comment by sandrotosi** [comment]
closed via #536
