### ISSUE TITLE
[QUESTION] Location of action files

### ISSUE THREAD

**Issue by dglava** [puddletag/puddletag#538]
Is there a reason why action files get saved under `~/.local/share/applications/Puddletag/actions` and not in the config directory? It's just a minor inconvenience when backing up settings, but I was wondering if there's a specific reasoning behind it, and if not, if it could be moved to the configuration directory?

**Comment by samuraibrian** [comment]
Or ~/.local/share/plugins as it happens to be on my Ubuntu 18.04 system... :-) (Puddletag 1.2.0)
