### ISSUE TITLE
Debian menu/desktop integration?

### ISSUE THREAD

**Issue by rmlrml** [puddletag/puddletag#540]
Hello, I'm so glad I found this repository, it's my favorite tag editor.  Debian hasn't been tracking puddletag since 1.2.0-2, it's no longer in testing or unstable and is going to disappear, and the stable version won't install on this (sid) system.

So the installation of prerequisites, git cloning, and running the program works perfectly per your instructions.  What would you recommend I do to fully 'install' and have PATH and menu integration?

**Comment by sandrotosi** [comment]
jfyi at some point i'm going to re-introduce puddletag to debian, i just didnt have the time to do so

**Comment by sandrotosi** [comment]
I've uploaded Puddletag to Debian, and it's currently in our new-project review queue; it may take a few weeks to get accepted, but when that'll happen, there's gonna be an entry in the Debian menu under "Sounds & Video"
