### ISSUE TITLE
Puddletag 2.0.1 - no Actions

### ISSUE THREAD

**Issue by Pastim** [puddletag/puddletag#549]
Good to see a release of puddletag for the future.  Thanks for your work.

I have run it, but have one problem. Neither Actions or Quick appear when I select from the menu (or the shortcut).

**Comment by Pastim** [comment]
By the way I'm running Ubuntu 20.04 (shortly to move on to 20.10).

**Comment by Pastim** [comment]
I can't use this version of puddletag, and will reluctantly have to revert to the appimage version.  Without Action macros, puddletag is, sadly. almost no use to me.

I seem to recall pointing this out on an early version of the QT5 version.  If I haven't made the issue clear, please let me know.

If there is anything I can check or test, please let me know.

**Comment by blueblots** [comment]
hi pastim, when I open the actions/quick actions dialog I can see some
actions showing up (I'm running puddletag from a git repository, on
openSUSE tumbleweed):

Can you elaborate on what you're doing step by step, and explain what
your expecting to see and what actually happens, with screenshots if it
makes things clearer.
In addition have you tried running puddletag from the terminal, if you
can do that you might get an error message in the output (which could
help us fix the problem).

**Comment by Pastim** [comment]
I now see that I raised this on a pre-release version as #510  - I'll carry on commenting there and close this one.

Apologies.
