### ISSUE TITLE
Unable to locate package puddletag on Ubuntu

### ISSUE THREAD

**Issue by egvimo** [puddletag/puddletag#569]
I've tried to install the new version of puddletag on my Ubuntu 20.10 system.
According to the readme this command should work:
```shell
sudo apt install puddletag
```
But I am getting the error:
```shell
Unable to locate package puddletag
```
What am I doing wrong?

By the way, I found a [snap package of puddletag](https://snapcraft.io/puddletag-snap) in the repositories. Is this an official one?

**Comment by sandrotosi** [comment]
According to the readme installation section https://github.com/puddletag/puddletag/#installation , Ubuntu is not listed there so it's not available. Please contact the Ubuntu user support forum appropriate to request new packages and bring this situation to their attention.

**Comment by sandrotosi** [comment]
> By the way, I found a [snap package of puddletag](https://snapcraft.io/puddletag-snap) in the repositories. Is this an official one?

if by official you mean "released and support by the puddletag developers" the answer is no, but i guess that's mostly true for all the other distributions package anyway.

**Comment by egvimo** [comment]
> According to the readme installation section https://github.com/puddletag/puddletag/#installation , Ubuntu is not listed there so it's not available. Please contact the Ubuntu user support forum appropriate to request new packages and bring this situation to their attention.

You are right. Ubuntu is not listed there. But Debian is.
Maybe I thought it would also work on Ubuntu because [the docs](https://docs.puddletag.net/download.html#installing-on-ubuntu) are mentioning it.

**Comment by sandrotosi** [comment]
yeah i really need to refresh the doc, as it may no longer be up to date
