### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by sbstn87** [puddletag/puddletag#578]
Hi, have you considered releasing a Windows version of Puddletag? I can see it is made with Python and Qt5, so this shouldn't be an issue.

Best regards.

**Comment by sandrotosi** [comment]
I'm not sure what you mean by "windows version" - did you try to install puddletag in windows and it didnt succeed or are you expecting some specific method for delivering puddletag on windows machines?

**Comment by sbstn87** [comment]
I had a standard Windows installer in mind.

**Comment by sandrotosi** [comment]
are you going to contribute one? otherwise i think it's unlikely we would (or even if it's the right approach, in general)

**Comment by sbstn87** [comment]
Unfortunately I do no know how to do it. Thanks for the reply.

**Comment by sandrotosi** [comment]
since it's unlikely any of the developers will prepare a windows-specific installer, i'm going to close this report. the most appropriate solution is going to be likely #431
