### ISSUE TITLE
How do I acheive copying %artist% to %albumartist%

### ISSUE THREAD

**Issue by bonelifer** [puddletag/puddletag#579]
I'd like to be able to have an action that allows me to copy the %artist% tag to %albumartist% in the ACTIONS functions. Not sure how to do that, even after looking at the action options currently available.

**Comment by audiomuze** [comment]
![image](https://user-images.githubusercontent.com/6852511/107193684-c5b8e700-69f7-11eb-97a1-a08011d2efaa.png)
