### ISSUE TITLE
does not recognize VLC

### ISSUE THREAD

**Issue by Antonio-52** [puddletag/puddletag#596]
Environment:
Puddletag v.2.0.1
OS: Ubuntu 18.03
Player: VideoLAN VLC 3.0.8 Vetinari

Hi !
To play mp3 files with VLC, in Edit >Preferences >General I set **Program to play files with: /usr/bin/vlc**
(the same command specified in my VLC.desktop, that runs OK in my terminal).
Now, after right-click >play Puddletag display an error message saying "...the music player you defined (/usr/bin/vlc) does not exists".
I tried to change to '/usr/bin/vlc' but it does not work.

**Comment by blueblots** [comment]
Hi @Antonio-52 , I've just tried to replicate your issue, but it's working fine for me. Is there any more detail you could provide to help me pinpoint the problem?

**Comment by sandrotosi** [comment]
@Antonio-52 i just tried too (i'm on Debian), and i can use VLC just fine, so it looks like there's either a configuration issue on your machine, or the way you installed puddletag/2.0.1 on that old Ubuntu release you're using is not correct.
