### ISSUE TITLE
Actions not working

### ISSUE THREAD

**Issue by Pastim** [puddletag/puddletag#602]
I thought I should try puddletag 2.0.1-2 on ubuntu 21.04, as opposed to the master copy I downloaded in Feb 2021.

I can't see any of my Actions.  Have they moved in the directory structure?

**Comment by Pastim** [comment]
It seems that the problem I had last year is still there

File "/usr/lib/python3/dist-packages/puddlestuff/functions.py", line 777, in to_ascii
    return ''.join(c for c in cleaned_fn if c in VALID_FILENAME_CHARS)
  File "/usr/lib/python3/dist-packages/puddlestuff/functions.py", line 777, in <genexpr>
    return ''.join(c for c in cleaned_fn if c in VALID_FILENAME_CHARS)
TypeError: 'in <string>' requires string as left operand, not int

For some reason I thought it had been fixed.

**Comment by sandrotosi** [comment]
This was fixed in #554 but it has not been released yet.

**Comment by Pastim** [comment]
OK - sorry.  I have tried to work out what's in the ubuntu version vs master, but can't find a way to do so, so I assumed an October fix might have made it's way through.
