### ISSUE TITLE
Scripting function: $sub won't accept field reference as argument

### ISSUE THREAD

**Issue by r3times** [puddletag/puddletag#612]
I'm trying to fill the 'Title' field with chapter numbers from the populated 'Track' field, using the '$sub' function to account for the mismatched chapter and track numbers for an audiobook. Instead I get the error message shown:

![ptagerr](https://user-images.githubusercontent.com/57061740/120360066-42056c00-c300-11eb-8bd7-d528ae023be0.jpg)

Am I doing something wrong, or is this simply unsupported in Puddletag? I'm using Puddletag 2.0.1 on Xubuntu 20.04.

**Comment by audiomuze** [comment]
sub() expects numbers only as parameters and subtracts the 1st from the 2nd.  Assuming all you're after is populating ```title``` with ```Chapter 01``` etc just use Format value with Format string: ```Chapter $num(%track%,2)```

**Comment by r3times** [comment]
Thanks, audiomuze - my question was prompted by the occasional tracks whose chapter numbers don't align with the track number, something that the equivalent sub() function in the mp3tag Windows program is able to accommodate.

As your example shows, it's trivial to play around with the track numbers to bulk rename the majority of files, before renumbering the tracks again to rename those first few edge cases.

**Comment by r3times** [comment]
.
