### ISSUE TITLE
Puddletag 2.0.1 not showing stored tags that were visible in previous versions (1.0.x)

### ISSUE THREAD

**Issue by dannn-o** [puddletag/puddletag#615]
I've built a new Linux Mint 20.1 (Ubuntu 20.04) computer to replace my Linux Mint 19.3 box.  I installed Puddletag 2.0.1 from the PPA, and am finding that the stored tags being displayed are incomplete.  One of the primary tags I'm interested in is unsyncedlyrics, but there are others that don't appear to display such as mediatype, originalreleasetime, and track: x/y.  I looked through the Preferences but didn't see any expand the tags shown.

**Comment by dannn-o** [comment]
Just noticed my CPU utilization was very high, and I found 7 entries for Puddletag even though I had exited all open windows.  Some of my music folder are stored on the network, in case that might matter.

**Comment by dannn-o** [comment]
Guess I'll update my own Issue again...Tried installing the SNAPD version of Puddletag, but encountered an error when trying to enable the "Stored Tags" window:

> QLabel(str, parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'bytes'
Aborted (core dumped)

Appears this has already been reported (issue #590, for example).  I also think my 2nd post about the CPU utilization may have been reported in #568.  Looking pretty rough for getting a working version of Puddletag in Mint 20.1 / Ubuntu 20.04.......

**Comment by sandrotosi** [comment]
please do not post different problems under a same issue, it makes it more complicated to follow up with questions or solution.

I am going to focus only of the first message, as the other 2 have issues opened already.

Can you clarify where in the puddletag UI you can find the fields you're interested in? is it the main window or somewhere else? screenshots are fine.

i checked the source code and we do have some references to `unsyncedlyrics`, but it seems support is limited

**Comment by dannn-o** [comment]
You'll notice I included links to the other open issues - wasn't trying to report them, only was referencing them in case they might be related.

I tracked down an Appimage version  (1.2.0) of Puddletag and have been using it with Mint 20 for the time being.  That's what I'm using to provide these screen shots, demonstrating the tags I mentioned in the original post:
![Screenshot from 2021-10-04 08-23-38](https://user-images.githubusercontent.com/17674969/135850727-920a4035-67ec-4797-8c07-707f1836a84a.png)


![Screenshot from 2021-10-04 08-24-34](https://user-images.githubusercontent.com/17674969/135850843-c6c0f07d-3121-4ae5-876c-553a29155af1.png)
![Screenshot from 2021-10-04 08-25-13](https://user-images.githubusercontent.com/17674969/135850922-b9b45fa4-add4-42aa-9725-6a9b87590ab3.png)

**Comment by sandrotosi** [comment]
I dont have any music file with that field, but i enabled the "Stored tag" section in the Window menu, and then right click on a track, Extended Tags, added a custom `unsyncedlyrics` field and that showed up in the stored tags section.

Are you saying that, with puddletag 2, you cannot visualize those tags even tho the file has them?

**Comment by sandrotosi** [comment]
please note the puddletag developers do not support that PPA, if you want to keep using it, please contact to the person who created it for support, not us.

If you want our help, please follow the steps at https://github.com/puddletag/puddletag#installation to install from source code and let us know if the problem still occur.

**Comment by dannn-o** [comment]
It's been a while so I thought I'd check in on this open issue.  I'm not sure why it's marked as needing "more-information", but please let me know if I can help provide anything specifically.  I noticed that version / release 2.1.1 made available a few days ago, so I installed it (from source) on my test machine and reran my tests:
![Screenshot from 2022-02-09 14-03-38](https://user-images.githubusercontent.com/17674969/153271820-324625f5-c86b-463b-b8ae-c3b3889185f8.png)

However, the "Stored Tags" panel is still not showing many of the tags expected.  
![Screenshot from 2022-02-09 14-06-01](https://user-images.githubusercontent.com/17674969/153272110-9e395fe1-0c56-4cdc-ac37-fca99b645c8e.png)

Something interesting I noticed:  In version 2.1.1, I am able to view / edit the "Extended tags" using the right-click option.  However, in version 2.0.1, right-clicking displayed the "Extended tags" option, but left-clicking on that option to select it does nothing.

Also, the CPU is still maxing out with version 2.1.1.
