### ISSUE TITLE
Readme.md correction Fedora distribution

### ISSUE THREAD

**Issue by xenea** [puddletag/puddletag#616]
Typo in Readme.md section Installation Fedora (https://github.com/puddletag/puddletag#installation) 
The package installation command should be `"dnf install puddletag"` instead of  `"dns installl puddletag" `

![puddletag-puddletag-Powerful-simple-audio-tag-editor-for-GNU-Linux](https://user-images.githubusercontent.com/19697841/122096696-744cb880-ce2c-11eb-964c-2b406df7392a.png)

**Comment by sandrotosi** [comment]
thanks @xenea , would you like to open a PR to fix this? you can do that entirely from the browser (in case you dont want to git clone, etc)

**Comment by xenea** [comment]
Hello @sandrotosi , It's done on new PR #617

**Comment by sandrotosi** [comment]
thanks! i've edited the PR description so that it would close this issue too
