### ISSUE TITLE
'An unhandled error occured: string indices must be integers'

### ISSUE THREAD

**Issue by Beckfield** [puddletag/puddletag#622]
I decided to try the Tag Sources feature for the first time.  I have an album of music files with no tags in them at all.  All files are .flac.  I initially used Puddletag to delete all tags in the files before starting.

1. I selected all the files, then opened the Tag Sources window.  
2. Set Source to MusicBrainz and entered the album title in the Search field. Clicked 'Search.'
3. Found the correct album from the search results.  Clicked on it.

The first time I did this, the Search list item expanded to show the tracks for the album.  Puddletag switched to Preview Mode, and many of the tags for the files showed the populated values.  I clicked 'Write,' and Puddletag started to write the tags.  When it got to writing file number 4 (10 total), it stopped, with the 'Writing...' dialog still showing.  After a few minutes, I clicked 'Cancel.'  I verified that the first 3 tracks were written to correctly, but tracks 4 - 10 were untagged.  I clicked 'Write' again, and nothing happened.
I closed the Tag Sources window and re-opened it to try again.  After finding the album again, clicking on it just reports "an unhandled error occured(sic): string indices must be integers."

Now, repeating the process with this or any other album results in the same error, even after closing Puddletag and restarting it.

OS: Linux Mint 20.2 64-bit running Cinnamon desktop
![image](https://user-images.githubusercontent.com/4588823/129517213-953d20bc-0585-4ef1-a55b-af826f89f77b.png)
![image](https://user-images.githubusercontent.com/4588823/129517312-220ebc93-9935-4751-92e5-9cbec1030658.png)

**Comment by Beckfield** [comment]
I have not seen this issue in quite a while now.  Hard to say if some linux update fixed something, but I'll keep an eye out.

**Comment by sandrotosi** [comment]
i'll close this in the meantime, feel free to reopen if it happens again in the future -- thanks!
