### ISSUE TITLE
Cannot see softlinked directory.  It contains all my audio tracks I need to tag.

### ISSUE THREAD

**Issue by Budgie2** [puddletag/puddletag#624]

**Comment by sandrotosi** [comment]
please provide more details

**Comment by Budgie2** [comment]
Entered too soon.  Please forgive.  New installation of openSUSE Leap 15.3.  All my multimedia data is on a separate RAID array and soft linked to my ~/multimedia/Music directory.  
I couldn't get puddletag installed from repo sites so used snap package which installed without a hitch. However having started the app, when I look for the required directory /multimedia, it is not there.  I have seen reports of issues with removable drives but this should work.  Have I missed something when I set up puddletag?.

**Comment by sandrotosi** [comment]
@Budgie2 i see you closed this bug report: are you still having issues? I tried to reproduce this on my system (debian unstable) and i was able to open a symlink just fine
