### ISSUE TITLE
Add "Rating" file metadata as a field 

### ISSUE THREAD

**Issue by Victor239** [puddletag/puddletag#630]
In KDE Dolphin and Elisa it's possible to give songs a star rating (up to 5 stars). In Dolphin this can be done by right-clicking a song > properties > details > rating.

I have most of my existing songs already tagged this way, so it would be great to be able to edit these ratings within puddletag.

**Comment by sandrotosi** [comment]
sorry to disappoint you, but puddletag is meant to be a cross-platform mp3 tag editor, so we wont support something KDE specific

**Comment by bernd-wechner** [comment]
Just a heads up that this may not be KDE specific (and it may be). The thing is there are commonly use Ratings fields that are used across lots of clients. From memory it's not very well standardised alas.

**Comment by sandrotosi** [comment]
and again, this is not really part of an audio tag editor, as rating is not part of audio tags

**Comment by bernd-wechner** [comment]
I store them there as do many I suspect, so they port with my library. That said, there are a number of standards I have to support ;-)

**Comment by Victor239** [comment]
It sounds like a chicken and egg problem - there's no Rating field that puddletag includes because various clients use different fields, but there will be no standardised field unless puddletag chooses which one to support. 

I don't really mind if the Rating field chosen isn't KDE's one, but I would like some sort of Rating audo tag within puddletag. I'm tired of adding ratings to songs via a particular music application, then it being inaccessible via any other application. It makes the most sense to me that it'd be an audio tag, since like @bernd-wechner said at least it's portable then.

**Comment by Victor239** [comment]
Ah I see that Popularimeter is the typical field for this, and it's also what KDE is already using for their Rating field. Looks like this already exists then, my apologies. It could maybe use with being called "Popularimeter (rating)" to inform newbies like myself.

**Comment by sandrotosi** [comment]
> Ah I see that Popularimeter is the typical field for this, and it's also what KDE is already using for their Rating field. Looks like this already exists then, my apologies. It could maybe use with being called "Popularimeter (rating)" to inform newbies like myself.

i think we're just using the name of the field in ID3v2: https://en.wikipedia.org/wiki/ID3#ID3v2_frame_specification
