### ISSUE TITLE
Column sizes reset when clicking "Ok" in Preferences

### ISSUE THREAD

**Issue by xeruf** [puddletag/puddletag#640]
If the columns are not set to fit to content, they all shrink together upon confirming the preferences, which is super annoying as I would like to keep them at a specific size.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/13354331/137582590-e496947f-fe81-4a1d-8d3a-a5e1d6bec2e4.png">
PS: Would be nice if I could copy the version info from about rather than having to type it out or screenshot it ;)

**Comment by sandrotosi** [comment]
> If the columns are not set to fit to content, they all shrink together upon confirming the preferences, which is super annoying as I would like to keep them at a specific size.

yup, i can confirm this with the latest git snapshot

> 
> <img alt="image" width="264" src="https://user-images.githubusercontent.com/13354331/137582590-e496947f-fe81-4a1d-8d3a-a5e1d6bec2e4.png">
> 
> PS: Would be nice if I could copy the version info from about rather than having to type it out or screenshot it ;)

this will be taken care of with #552

**Comment by xeruf** [comment]
Seems to work fine, thank you, finally :)
