### ISSUE TITLE
NameError: name 'operatorPrecedence' is not defined

### ISSUE THREAD

**Issue by wazabees** [puddletag/puddletag#643]
I am getting the error below trying to start Puddletag v2.0.1.

OS: Arch linux, 5.14.14-arch
Python 3.9.7

```
╰─❯ puddletag     
puddletag Version: 2.0.1
Locale: en_GB
Traceback (most recent call last):
  File "/usr/bin/puddletag", line 333, in <module>
    from puddlestuff.puddletag import MainWin
  File "/usr/lib/python3.9/site-packages/puddlestuff/puddletag.py", line 12, in <module>
    from . import mainwin
  File "/usr/lib/python3.9/site-packages/puddlestuff/mainwin/__init__.py", line 4, in <module>
    from . import dirview
  File "/usr/lib/python3.9/site-packages/puddlestuff/mainwin/dirview.py", line 12, in <module>
    from ..tagmodel import has_previews
  File "/usr/lib/python3.9/site-packages/puddlestuff/tagmodel.py", line 31, in <module>
    from .audio_filter import parse as filter_audio
  File "/usr/lib/python3.9/site-packages/puddlestuff/audio_filter.py", line 183, in <module>
    bool_expr = operatorPrecedence(tokens, bool_exprs)
NameError: name 'operatorPrecedence' is not defined
```

**Comment by ArveMediaconnect** [comment]
Seems like this operatorPrecedence thing was removed from pyparsing 3.

https://pyparsing-docs.readthedocs.io/en/latest/whats_new_in_3_0_0.html#id21

**Comment by sandrotosi** [comment]
@wazabees @ArveMediaconnect @gitdwarf can you tyr to edit `/usr/lib/python3.9/site-packages/puddlestuff/audio_filter.py` (it may require sudo) to replace `operatorPrecedence` with `infixNotation` and let me know if it works? thanks!

**Comment by ArveMediaconnect** [comment]
As I mentioned, changing it to infix_notation worked for me, and as far as I understand it, infixNotation is just an alias for infix_notation, so should work the same (maybe even better, I don't know if infix_notation is available in older versions of pyparsing).

**Comment by gitdwarf** [comment]
Hi there
Yes, I can also confirm, that changing operatorPrecedence in
site-packages/puddlestuff/audio_filter.py
to EITHER
infix_notation
OR
infixNotation
both resolves the issue :)

**Comment by wazabees** [comment]
Confirmed for me as well, replacing `operatorPrecedence` with `infixNotation` solved the issue. Thanks! :)

**Comment by trisweb** [comment]
Still running into this with the latest release. Was the fix ever released?
