### ISSUE TITLE
Editing "Extended Tags" on an AIFF sporadically results in "TypeError: cannot use a string pattern on a bytes-like object"

### ISSUE THREAD

**Issue by unilock** [puddletag/puddletag#646]
I'm having some difficulties editing AIFF files.

Editing Extended Tags on a single AIFF file works fine. No output on the command line, and the GUI opens the Extended Tags windows as expected.

Editing Extended Tags on one AIFF and another file simultaneously (even another AIFF) does *not* work. I get the below traceback no matter what other audio file type I'm trying to edit.

`lsb_release -a`:
```
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute
```

puddletag info:
```
puddletag Version: 2.0.1
Locale: en_US
```

Trying to edit the Extended Tags of both an AIFF and e.g. an MP3 simultaneously:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/mainwin/funcs.py", line 198, in extended_tags
    win = helperwin.ExTags(files=status['selectedfiles'], parent=parent)
  File "/usr/lib/python3/dist-packages/puddlestuff/helperwin.py", line 718, in __init__
    self.loadFiles(files)
  File "/usr/lib/python3/dist-packages/puddlestuff/helperwin.py", line 918, in loadFiles
    self._settag(row, field, values, multi=True)
  File "/usr/lib/python3/dist-packages/puddlestuff/helperwin.py", line 1100, in _settag
    valitem = StatusWidgetCombo(value, status, self._colors, preview)
  File "/usr/lib/python3/dist-packages/puddlestuff/helperwin.py", line 520, in __init__
    items = sorted(items, key=natsort_case_key)
  File "/usr/lib/python3/dist-packages/puddlestuff/puddleobjects.py", line 628, in natsort_case_key
    return [convert(c) for c in re.split('([0-9]+)', s)]
  File "/usr/lib/python3.9/re.py", line 231, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object
```

This issue goes along with my other issue at #645.

Let me know what you think.

EDIT: *Sometimes,* editing the Extended Tags of an AIFF won't work, even if it's the only file loaded. Also, doing so occasionally won't work when the AIFF is *loaded* with another file, but not *selected* with another file (so, only the AIFF's extended tags would be being edited). All with the same traceback, above.

You think programming puddletag is hard, imagine having to report its arcane issues!! \<\/s\>

**Comment by corubba** [comment]
Can reproduce this on Pop!_OS 21.04 with the native puddletag package (v2.0.1) and your aiff file from #645. Using the current `master` branch the error does not occur however, so I am closing this as solved.
