### ISSUE TITLE
Crash when trying to filter non alphabetical characters

### ISSUE THREAD

**Issue by RafaelLinux** [puddletag/puddletag#665]
Puddletag 2.0.1

While having a list of audio files and I try to filter by any non alphabetical or numeric character (like "-", "—", "[" ... without double quotation marks) , Puddletag crashes just after hitting <Intro> or click in "Go" button. 

Apart from this bug, I have to comment that when I click on "Help, Bug tracker" in Puddletag, to report a bug, the page https://code.google.com/archive/p/puddletag/ opens, which does not allow to open an incident. They should change the link or add another option under "Help" that redirects to this GitHub page.

Thank you

**Comment by sandrotosi** [comment]
> Puddletag 2.0.1
> 
> While having a list of audio files and I try to filter by any non alphabetical or numeric character (like "-", "—", "[" ... without double quotation marks) , Puddletag crashes just after hitting or click in "Go" button.

can you please provide the traceback? you can obtain one by repeating the action causing puddletag to crash by running it in a terminal

> Apart from this bug, I have to comment that when I click on "Help, Bug tracker" in Puddletag, to report a bug, the page https://code.google.com/archive/p/puddletag/ opens, which does not allow to open an incident. They should change the link or add another option under "Help" that redirects to this GitHub page.

that's already been taken care of on git, you can run puddletag from source as explained [here](https://github.com/puddletag/puddletag#installation)

**Comment by RafaelLinux** [comment]
> can you please provide the traceback? you can obtain one by repeating the action causing puddletag to crash by running it in a terminal
> 

Next is the output just after trying to filter by "-"
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/puddlestuff/tagmodel.py", line 1526, in applyFilter
    self.model().applyFilter(pattern, matchcase)
  File "/usr/lib/python3.6/site-packages/puddlestuff/tagmodel.py", line 648, in applyFilter
    filtered = [(filter_audio(a, pattern), a) for a in self.taginfo]
  File "/usr/lib/python3.6/site-packages/puddlestuff/tagmodel.py", line 648, in <listcomp>
    filtered = [(filter_audio(a, pattern), a) for a in self.taginfo]
  File "/usr/lib/python3.6/site-packages/puddlestuff/audio_filter.py", line 190, in parse
    res = bool_expr.parseString(expr)[0]
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 3003, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected {'not' term | 'or' term}, found '-'  (at char 0), (line:1, col:1)
Abortado (`core' generado)
```
> 
> that's already been taken care of on git, you can run puddletag from source as explained [here](https://github.com/puddletag/puddletag#installation)

There is not explanation about openSUSE (anyway, it's sudo zypper in puddletag)

**Comment by sandrotosi** [comment]
> > that's already been taken care of on git, you can run puddletag from source as explained [here](https://github.com/puddletag/puddletag#installation)
> 
> There is not explanation about openSUSE (anyway, it's `sudo zypper in puddletag`)

it is:

```
First, you need to install the dependencies; this step is different depending on the distribution;...

git clone https://github.com/puddletag/puddletag
cd puddletag
PYTHONPATH=source/ ./source/puddletag
```

**Comment by RafaelLinux** [comment]
I tried with GIT version of puddletag, and exactly same output.
