### ISSUE TITLE
Puddletag doesn't use system theme anymore

### ISSUE THREAD

**Issue by JoeJoeTV** [puddletag/puddletag#700]
### The Issue

I have recently updated puddletag using pip and after the update, puddletag didn't use my system dark theme or any theme set using the qt5 settings and instead uses the standard light theme.
It used the system theme before I updated, which was a version I downloaded late last year IIRC.

### Specs

- OS: Linux Mint Cinnamon 20.3
- Puddletag Version: 2.1.1

**If any more information is needed, I'll gladly provide it!**

**Comment by plumber-craic** [comment]
thanks - i had no idea you could override themes like this. After installing kvantum for qt5 I was able to get darkmode working by changing this line in puddletag.desktop:
Exec=env QT_STYLE_OVERRIDE=kvantum-dark puddletag %F

Needed to verify that kvantum-dark was available with this:
python3 -c "from PyQt5.QtWidgets import QStyleFactory; print(QStyleFactory.keys())"
