### ISSUE TITLE
Add `pyproject.toml`

### ISSUE THREAD

**Issue by corubba** [puddletag/puddletag#703]
Under the umbrella of the [Python Packaging Authority](https://www.pypa.io/), the guidelines and best practises for packaging python projects are constantly evolving. In recent times there was a push towards using a standardised and universal `pyproject.toml` for specifying the used build tools/dependencies ([PEP-517](https://www.python.org/dev/peps/pep-0517/) and [PEP-518](https://www.python.org/dev/peps/pep-0518/)), and also general project metadata like name and dependencies ([PEP-621](https://www.python.org/dev/peps/pep-0621/) and [PEP-631](https://www.python.org/dev/peps/pep-0631/)). I can recommend [this blog post](https://snarky.ca/what-the-heck-is-pyproject-toml/) if you want a quick overview.

Like many (if not most) other Python projects, puddletag uses [setuptools](https://setuptools.pypa.io/) as its build system. While it is PEP-517 compliant and provides in its [docs](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use) an example of what a `pyproject.toml` should look like, it does not yet [fully support](https://github.com/pypa/setuptools/issues/1688) the new file as its only source of information and still relies on `setup.cfg` and/or `setup.py` to provide them.

As a first step and general future-proofing, I propose to add a basic `pyproject.toml` to explicitly specify used the build-backend and build-dependencies. There should be no need to change anything on the setuptools config. Building/Packaging puddletag using a PEP-517 build-frontend like [pypa-build](https://pypa-build.readthedocs.io/) should work out-of-the-box. I am confident that we do not need the backwards-compatibility provided by the [`setuptools.build_meta.__legacy__`](https://github.com/pypa/setuptools/blob/main/setuptools/build_meta.py#L253) backend.
Optionally, it may be worthwhile to move the static parts from `setup.py` to a `setup.cfg` file. Separating static from dynamic parts should ease the evaluation of our build system requirements, and also the (I believe eventual) migration to `pyproject.toml`-only in the long term.

**Comment by sandrotosi** [comment]
yeah i think we should just migrated to pyproject.toml and remove entirely the only setup.py infrastructure. im fairly agnostic on the backend to use, poetry is powerful but may be more than we need, we could stick to setuptools not to introduce another dependency or `flit` which i dont know much

**Comment by corubba** [comment]
On a related note, the `setup.py` currently does some weird import stuff, sometimes importing from `setuptools` and sometimes from `distutils` directly. Looking at `git blame`, those were added ~10 years ago and need re-evaluation.
As per [PEP-632](https://www.python.org/dev/peps/pep-0632/) the distutils module is deprecated and will be removed with python v3.12 from the stdlib. `setuptools` now ships with its own copy of distutils, we will have to see if and what breaks.
This also sheds a new light on the build changes in #687, I will have to rethink/revisit those.
