### ISSUE TITLE
"AttributeError: 'QComboBox' object has no attribute 'textActivated'" runnning puddletag from latest source

### ISSUE THREAD

**Issue by dannn-o** [puddletag/puddletag#709]
Saw my issue #615 was closed last month so thought I'd try some testing again (running from source).
This time, puddletag was failing to launch with the error mentioned in the issue subject line.
I double-checked all of the python3 dependencies and they show being at the latest levels.

Here is output from the terminal session:
```
tester@Mint20Test:~$ git clone https://github.com/puddletag/puddletag
Cloning into 'puddletag'...
remote: Enumerating objects: 11046, done.
remote: Counting objects: 100% (1075/1075), done.
remote: Compressing objects: 100% (575/575), done.
remote: Total 11046 (delta 680), reused 746 (delta 463), pack-reused 9971
Receiving objects: 100% (11046/11046), 37.87 MiB | 5.65 MiB/s, done.
Resolving deltas: 100% (7694/7694), done.
tester@Mint20Test:~$ cd puddletag
tester@Mint20Test:~/puddletag$ PYTHONPATH=source/ ./source/puddletag
bash: ./source/puddletag: No such file or directory
tester@Mint20Test:~/puddletag$ python3 puddletag
puddletag Version: 2.1.1, Changeset: a0d4ab4b22d04575fcf974cb1086293468ccf6d4
qt5ct: using qt5ct plugin
Locale: en_US
Traceback (most recent call last):
  File "puddletag", line 344, in <module>
    win = MainWin()
  File "/home/tester/puddletag/puddlestuff/puddletag.py", line 330, in __init__
    winactions, self._docks = create_tool_windows(self)
  File "/home/tester/puddletag/puddlestuff/puddletag.py", line 85, in create_tool_windows
    p = PuddleDock(z[0], z[1], parent, status)
  File "/home/tester/puddletag/puddlestuff/puddleobjects.py", line 2339, in __init__
    control = control(status=status)
  File "/home/tester/puddletag/puddlestuff/mainwin/filterwin.py", line 56, in __init__
    self.combo.combo.textActivated.connect(
AttributeError: 'QComboBox' object has no attribute 'textActivated'
tester@Mint20Test:~/puddletag$ 
```

Tried deleting the entire github cloned directory and ran through it again, but with the same results.

Specs are:
OS - Linux Mint 20.3 
DE - Cinnamon 5.2.7
Linux Kernel - 5.4.0-99

**Comment by corubba** [comment]
[`QComboBox.textActivated`](https://doc.qt.io/qt-5/qcombobox.html#textActivated) was introduced in Qt v5.14, we changed to it in preparation for PyQt6. Linux Mint 20.3 ships with Qt v5.12 (and PyQt v5.14 :raised_eyebrow:) which obviously won't work then. The easiest solution is probably to run puddletag in a virtualenv, which will pull in a more recent version of Qt via pip.

@sandrotosi Your thoughts on backward compatibility? Qt v5.12 was the last v5 LTS and is EOL since 2021-12.

**Comment by dannn-o** [comment]
@corubba Thanks for the prompt reply.  I'm not sure what Mint 20.3 might include with a base install (I've taken the usual upgrade path from base install of v20 to 20.1, 20.2, 20.3), but the "python3-pyqt5" package is part of what's listed as required under "source code" installation directions (I run the "apt install" for all dependencies each time running puddletag from source), and my Synaptic package mgr. shows I have v **5.14.1+dfsg-3build1** installed, which also shows as what's included with Ubuntu Focal 20.04 LTS upstream.

This issue didn't happen when I installed / ran puddletag from source last month, before the fix for #615 (and other code since then) was committed, so it appears to possibly related to some other code change.  If there is any other dependency information or diagnostic data I can help provide, please let me know.

**Comment by corubba** [comment]
The issue is not PyQt but Qt itself. If you look for example what version of the [`libqt5core5a`](https://packages.ubuntu.com/focal/libqt5core5a) package you have installed (which is a dependency of [`python3-pyqt5`](https://packages.ubuntu.com/focal/python/python3-pyqt5)), you will see it is 5.12.something. With #705 the minimum version for Qt was (somewhat unintentionally) raised to v5.14.

**Comment by pedrobaeza** [comment]
As there are a lot of people in Ubuntu LTS 20.04 till the arrival of 22.04, I think a fallback should be applied for allowing to use it with libqt5core5a 5.12 (currently 5.12.8+dfsg-0ubuntu2.1 in my system).

**Comment by dannn-o** [comment]
I would also vote for backward compatibility for Qt as well, but I do already have a VM environment with puddletag installed (until I can get a stable version whether source, PPA, Appimage, whatever!, that will work again on Mint 20.x / Ubuntu 20.xx) so I don't mind upgrading libqt5core5a.  However, I haven't been able to find any supported package or PPA to help do that, and I'm not familiar with building QT 5 from source.

Right now, on my production (Mint 20.3) machine, I continue to use an Appimage for puddletag built with version 1.2.0.  However, it is clunky as it doesn't integrate well with right-click option from Nemo, etc.

**Comment by corubba** [comment]
Well, you can always go virtualenv. All you need are a few basic python things installed, all the rest (including a independent installation of Qt that matches the PyQt version we need) gets pulled in via pip. Something along the lines of:
```sh
apt install 'python3' 'python3-pip'
git clone 'https://github.com/puddletag/puddletag.git'
cd puddletag
python -m venv '.'
bin/pip install -r 'requirements.txt'
```

But yeah, keeping/restoring support for the last Qt v5 LTS version is reasonable.

**Comment by dannn-o** [comment]
Thanks for the tip.  For me, the whole environment is virtual (i.e. a VM running under VirtualBox, just for testing puddletag), so I skipped the python 'venv' command.  But running `pip3 install -r 'requirements.txt'` got QT 5.15.2 installed, along with the other components, and I was able to successfully launch puddletag afterward.
