### ISSUE TITLE
E: Unable to locate package puddletag

### ISSUE THREAD

**Issue by neesti** [puddletag/puddletag#732]
Hello.

I use Linux Mint 20.3 with Cinnamon desktop. Linux Mint is based on Ubuntu, but when I want to install puddletag on Linux Mint, it seems there is not this package on software repository!

`E: Unable to locate package puddletag`

**Comment by sandrotosi** [comment]
Please reach out to the proper Linux Mint support channel, as we dont control what software is provided in that distribution
