### ISSUE TITLE
Issues installing/running puddletag from the GIT repo

### ISSUE THREAD

**Issue by StevenPUlrick** [puddletag/puddletag#733]
This is on Fedora Linux 36.
I installed puddletag from the git repo in the following location:
"/usr/local/spu/assorted/p/puddletag/puddletag-20220519"
Before I installed puddletag, I placed the following in /root/.bash_profile:
PYTHONPATH=/usr/local/spu/assorted/p/puddletag/puddletag-20220519/local/lib/python3.10/site-packages:$PYTHONPATH

Here is the command I used to install puddletag:
/usr/bin/python3.10 setup.py install --prefix=/usr/local/spu/assorted/p/puddletag/puddletag-20220519

The issue is that when I click on the executable, it does not start. Then I tried running it from a terminal to see if that would get me any useful information. I got the following:
[steve@afolkey2 bin]$ ./puddletag 
Traceback (most recent call last):
  File "/usr/local/spu/assorted/p/puddletag/puddletag-20220519/local/bin/./puddletag", line 4, in <module>
    __import__('pkg_resources').run_script('puddletag==2.1.1', 'puddletag')
  File "/home/steve/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/steve/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/puddletag' not found in metadata at '/usr/lib/python3.10/site-packages/puddletag-2.1.1-py3.10.egg-info'
[steve@afolkey2 bin]$ 

Any ideas?

**Comment by sandrotosi** [comment]
Hello, this seems more a general installation question than something specific to puddletag (like a bug in our installation system), so i encourage you to contact a python user support forum.
