### ISSUE TITLE
Load specified directories from a file list

### ISSUE THREAD

**Issue by audiomuze** [puddletag/puddletag#743]
### What's missing?

Puddletag currently loads files by being pointed to a directory tree or incrementally adding individual folders.  Sometimes one wants to work only on a specific list of  folders, which are not necessarily in the same directory tree.

### Your solution

It'd be great if puddletag could be pointed to a text file containing a list of folders to load e.g:
somefile.txt
```
/alib/ext4e/B/Buckethead - Pike 11 [Limited Edition]
/alib/ext4e/B/Buckethead - Pike 12
/alib/ext4e/B/Buckethead - Pike 14 [Limited Edition]
/alib/ext4e/B/Buckethead - Pike 17
/alib/ext4e/B/Buckethead - Pike 21
/alib/ext4f/Buckethead/Buckethead - Forgotten Library
/alib/ext4f/Buckethead/Buckethead - Propellar
/alib/ext4f/Buckethead/Buckethead - Spiral Trackway
/alib/ext4f/Buckethead/Buckethead - The Mark of Davis
/alib/ext4f/Buckethead/Buckethead - The Spirit Winds
```

This could be accessed by passing a switch at the command line ```-loadlist somefile.txt``` and addition of a File  | Add Folders from File menu item.

### Any alternatives?

Manually and incrementally loading the relevant folders using File | Add Folder, which is painful if one has to navigate a large filesystem or directory tree.

**Comment by audiomuze** [comment]
You're working on the assumption that sets of discrete directories is the requirement here.  It's not.  If you're dealing with a large library and you've kept a list of albums that need metadata editing as you've come across issues whilst listening there comes a time to address those errors - this could be anywhere from 5 to 100 albums at a time and they could be located anywhere in the filesystem.  Under these circumstances being able to point puddletag to a file containing  a list of folders you'd like loaded for editing makes sense.

**Comment by sandrotosi** [comment]
Im in agreement with what @corubba is saying: there's already a mechanism to pass a list of directories to puddletag, altho it may not function exactly as OP envisioned.

@audiomuze while i understand your point, i dont see the benefit of having this feature added to puddeltag, in particular when you can already leverage the power of the linux shell, and maybe there are ways to "work around" your specific issue by adjusting your workflow (f.e. i used to have a directory dedicated to music that needed to be tagged/adjusted).
