### ISSUE TITLE
AttributeError with version 2.2.0

### ISSUE THREAD

**Issue by ranperry** [puddletag/puddletag#746]
### Current Behavior

Updated to the latest git stable version. When running puddletag, it craches with the following error:

ran@hp400:~/git/puddletag$ ./puddletag 
Traceback (most recent call last):
  File "./puddletag", line 339, in <module>
    import puddlestuff.constants
  File "/home/ran/git/puddletag/puddlestuff/constants.py", line 84, in <module>
    LEFTDOCK = Qt.DockWidgetArea.LeftDockWidgetArea
AttributeError: type object 'DockWidgetArea' has no attribute 'LeftDockWidgetArea'

### Expected Behavior

Pudddletag should launch properly as before

### Steps To Reproduce

1. Run git pull
2. run ./puddletag

### Information about your system

Puddletag: 2.2.0
OS: Linux Mint 19.3 Cinnamon
Python: 3 & 3.6
PyQt: 5

### Anything else?

Worked without any issue with 2.1

**Comment by sandrotosi** [comment]
works just fine here, @corubba any idea what's going on here?

**Comment by ranperry** [comment]
Updating to the latest PyQt version available (PyQt5-5.15.6) solved the issue. Thanks!
