### ISSUE TITLE
Error searching Discogs with version 2.2.0

### ISSUE THREAD

**Issue by ranperry** [puddletag/puddletag#755]
### Current Behavior

When searching for an album using Discogs, I get the following error:

An error occurred: local variable '_reference_time' referenced before assignment

### Expected Behavior

Puddletag will fetch the correct information from Discogs

### Steps To Reproduce

1. Install the latest version from Git (2.2.0)
2. Open a folder with audio files
3. Enable "tag Source"
4. From the sources drop down menu, choose Discogs
5. Enter the following number (or any number) 23253320
6. Click on Search
7. Puddletag will show an error "An error occurred: local variable '_reference_time' referenced before assignment"

### Information about your system

Puddletag: 2.2.0
OS: LinuxMint 19.3
Python 2.7.17
PyQt: 5.10.1

### Anything else?

Link for the screenshot:

https://imgur.com/a/3jtQ5gn

**Comment by sandrotosi** [comment]
appreciate the bug report, please next time type up the exception, as image are not easily searchable on gh

`An error occurred: local variable '__reference_time' referenced before assignment`

**Comment by ranperry** [comment]
Hmm... I did type this twice...

**Comment by beurotta** [comment]
In [puddletag/puddlestuff/tagsources/discogs.py](https://github.com/puddletag/puddletag/blob/master/puddlestuff/tagsources/discogs.py), adding

```python
global __reference_time
```

in the `urlopen()` function definition (starting on line 242), fixes the issue.



```python
def urlopen(url):
    global __reference_time
    url = iri_to_uri(url)
    request = urllib.request.Request(url)
    request.add_header('Accept-Encoding', 'gzip')
    request.add_header('User-Agent', get_useragent())
```

**Comment by ranperry** [comment]
Excellent! Many thanks!
