### ISSUE TITLE
MP4 mood tags not shown

### ISSUE THREAD

**Issue by weinimo** [puddletag/puddletag#770]
### Current Behavior

When reading MP4/M4A/AAC audio files puddletag does not show the mood tag of the files. It does write them though if they are added. I was able to confirm that the tags get written using my own little mutagen Python script. MP3 files do not seem to be affected.

### Expected Behavior

It should show the mood tags that were written to the file when loading it.

### Steps To Reproduce

1. Open a MP4 audio file
2. Add a mood tag to the file
3. Save
4. Reload puddletag and load the file again
5. Check if the mood tag is shown

### Information about your system

Puddletag: 2.2.0
OS: Fedora Linux 37 (Thirty Seven)
Python: 3.11.0
PyQt: 5.15.6
Qt: 5.15.7
Mutagen: 1.45.1
PyParsing: 3.0.9
ConfigObj: 5.0.6
lxml: 4.9.1
pyacoustid: 1.2.2
audioread: 3.0.0
Levenshtein: unknown version
Chromaprint: unknown version

### Anything else?

If needed I could help with a reproducer script that verifies the tags were written correctly.

**Comment by Switch123456789** [comment]
I just stumbled across the same issue with the arranger-tag, I am not sure if I understand it right but according to [this](https://docs.puddletag.net/source/tags.html#tags) a whole bunch of puddletag-fields are not associated to "MP4 Atoms" (including mood & arranger). It says "Any MP4 atoms not in this list will be assumed to be freeform frames". I really struggle to understand all of this to be honest but as far as I can tell it looks like puddletag struggles to load said "freeform frames" in general.
