### ISSUE TITLE
[Documentation] Install with pipx

### ISSUE THREAD

**Issue by lwbt** [puddletag/puddletag#773]
### What's missing?

I want to suggest [pipx](https://pypa.github.io/pipx/installation/) as another alternative installation method to add to the documentation/README.md and probably the new default installation method.

### Your solution

It could be as simple as:

```bash
pipx install puddletag

# To run puddletag, it should be on you PATH now:
puddletag
```

And that works well. When you know your way around Linux/FOSS and Python. More complete instructions would look like this:

```bash
# Linux installation of pipx taken from https://pypa.github.io/pipx/installation/
python3 -m pip install --user pipx
python3 -m pipx ensurepath

# Install Puddletag
pipx install puddletag

# Improve desktop integration with shortcut and icon
mkdir -pv "$HOME/.local/share/"{applications,icons}
ln -sv "$HOME/.local/pipx/venvs/puddletag/share/applications/puddletag.desktop" \
  "$HOME/.local/share/applications/"
ln -sv "$HOME/.local/pipx/venvs/puddletag/share/pixmaps/puddletag.png" \
  "$HOME/.local/share/icons/"

# You can run in from the command line, but it should have a functional icon
# like any other app in your app drawer now.
```

Upgrading to a newer version is as easy as:

```bash
pipx upgrade puddletag
```

Or if you want to upgrade all the other tools you installed with pipx to do `pipx upgrade-all`. When you switch to a newer Python version (e.g. distribution release upgrade), do `pipx reinstall-all`.

### Any alternatives?

Well there was Flatpak support which had been discussed and declined: https://github.com/puddletag/puddletag/issues/735

Someone is [publishing a snap](https://snapcraft.io/puddletag-snap), not sure if that is official, but as an Ubuntu user who also uses other Linux systems like Steam Deck, the best outcome for Snapd seems to be that it will be successful on Ubuntu while every other Linux distribution seems to avoid it in favor of Flatpak or other mechanisms (static binaries, AppImage, or pipx).

### Anything else?

It's apparently meant to be for CLI utilities (also supports generating Shell Completion for tools) but it works surprisingly well with Puddletag so far (I loaded up a few files and added a comment to the comment field of an album, but Puddletag worked well in a venv before and this is no different, just easier). I heard about it in [talkpython.fm](https://talkpython.fm/episodes/show/371/pipx-installable-isolated-python-applications) some time ago, but it took until today for me to look into it, because my experience with Python and Pip had been messy in the past and I'd thought it would be a _nice to have_ that is still super complicated to implement and convince maintainers to do so. But was very simple as you can seem.

I wish you all the best for your holidays.

**Comment by sandrotosi** [comment]
i think we wrote README.md installation section before we started publishing puddletag to PyPI. so what i think we should advertise it to use `pip` (i dont think there's any advantage is advertising pipx) to install puddletag

**Comment by sandrotosi** [comment]
I decided to go with

1. pypi
2. distro pkgs
3. source code

we'll see what reactions (if any) that'll bring, but i think advertise pypi first makes sense, given we immediately release there while with distro pkgs there's always a delay (in particular close to their releases, like it's happening now in Debian)
