### ISSUE TITLE
Name "Disable Preview Mode" more appropriately

### ISSUE THREAD

**Issue by xeruf** [puddletag/puddletag#788]
Maybe something like "Discard Changes and Exit Preview Mode", to make it clear that changes are discarded.
I thought it would write the changes on exit...

See also https://github.com/puddletag/puddletag/issues/196

**Comment by sandrotosi** [comment]
hey @corubba ! while trying to fix this, by modifying the text at https://github.com/puddletag/puddletag/blob/master/puddlestuff/tagmodel.py#L125 i realized that will also invalidate the translation files.

so i started looking at https://github.com/puddletag/puddletag/blob/master/update_translation.py which hasnt been ported propertly to python3 nor ptqt5, but anyway, is the right way to refresh the translation file to run `pylupdate5 -verbose puddletag.pro`? when i do that i got a lot of extra changes in the .ts files and i'm not sure if the are expected or not

**Comment by sandrotosi** [comment]
oh nevermind, i see that's tackled as part on #694 , so i can wait for it to be merged
