### ISSUE TITLE
System restarting issue

### ISSUE THREAD

**Issue by OuchenOussama** [puddletag/puddletag#815]
### Current Behavior

Using this on Ubuntu 22.04, when clicking the exit button, im logged out, and the login interface appears, with everything from the previous session comletely discarded, as if the system was restarted, this is not an issue when clicking on Quit via the app's icon in the taskbar tho.

### Expected Behavior

just close the program, no need to close every single thing

### Steps To Reproduce

i tried many things, it happened when i used the app to wipe data from mp3 files, and it also happened when i simply just opened and attempted to close right after.

### Information about your system

Puddletag: 2.2.0
OS: Ubuntu 22.04.2 LTS
Python: 3.10.6
PyQt: 5.15.6
Qt: 5.15.3
Mutagen: 1.45.1
PyParsing: 2.4.7
ConfigObj: 5.0.6
lxml: 4.8.0
pyacoustid: 1.2.2
audioread: 2.1.9
Levenshtein: unknown version
Chromaprint: unknown version

**Comment by sandrotosi** [comment]
please ask for help on a ubuntu users support forum, as this looks like some issue on your system; reopen if you can pin-point to a bug in puddletag
