### ISSUE TITLE
Empty mass tagger log

### ISSUE THREAD

**Issue by sonofevil** [puddletag/puddletag#832]
### Current Behavior

Mass tagger produces no log text. Only empty lines and a completion message.

Doesn't matter what profile settings I use.

![Screenshot_20230817_003917](https://github.com/puddletag/puddletag/assets/19374890/c417c6b3-eae9-4b83-9a85-700ec53525bf)

### Expected Behavior

Some kind of useful information about the track matching process is shown.

### Steps To Reproduce

1. Run mass tagger with any functional profile on any number of files.
2. Observe log.

### Information about your system

Puddletag: 2.2.0-2
OS: EndeavourOS
Python: 3.11.3-2
PyQt: 5.15.9-2 & 6.5.2-1

**Comment by therectifier** [comment]
I'm seeing this problem too... Using the Tag Sources thing works just fine, but using the same source (eg. MusicBrainz) with Masstagging returns more or less what you've shown here... Glad it's not just me being boneheaded...
