### ISSUE TITLE
File access

### ISSUE THREAD

**Issue by HRoyH** [puddletag/puddletag#863]
### Current Behavior

I  am using Puddletag 2.2 on Linux Mint 21.3 with kernel 5.15.0-91
My music files are on a separate partition, sd2 on mnt, which is mounted at startup, but puddletag can not be persuaded to look there for them

### Expected Behavior

I need to be able to access this partition from puddletag

### Steps To Reproduce

click on file tab

### Information about your system

Puddletag: 2.2.0
OS: KDE Flatpak runtime
Python: 3.10.13
PyQt: 5.15.9
Qt: 5.15.9
Mutagen: 1.46.0
PyParsing: 3.0.9
ConfigObj: 5.0.8
lxml: not installed
pyacoustid: not installed
audioread: not installed
Levenshtein: not installed
Chromaprint: not installed

**Comment by sandrotosi** [comment]
this seems like more a distro/local machine setup issue; can you browse the separate partition with a file browser using the same user account? if so, i dont see why puddletag wouldnt be able to access it as well

**Comment by sandrotosi** [comment]
> > OS: KDE Flatpak runtime
> 
> Educated guess: The Flatpak sandbox (filesystem isolation) hides it from puddletag.

ha-ah, good catch!

@HRoyH please follow any of the methods listed at https://github.com/puddletag/puddletag?tab=readme-ov-file#how-to-install, as the puddletag developers dont support the flatpak distribution mechanism

**Comment by HRoyH** [comment]
Ok, I'll check it out.

**Comment by HRoyH** [comment]
Thanks to all for responses. Flatseal does provide a means of altering that file access setting. A useful introduction for me to Flatseal/Flatpak under the bonnet stuff. Thanks again.
