### ISSUE TITLE
Puddletag on Flatpak freezes on opening SMB network share

### ISSUE THREAD

**Issue by rgoubet** [puddletag/puddletag#908]
### Current Behavior

I have an SMB network share mounted from Nautilus. I have set the permissions for the app based on the documentation found [here](https://docs.flatpak.org/en/latest/sandbox-permissions.html#gvfs-access).

The file `/var/lib/flatpak/overrides/net.puddletag.puddletag` has the following content:

```
[Context]
filesystems=xdg-run/gvfsd;xdg-run/gvfs;

[Session Bus Policy]
org.gtk.vfs.*=talk
```

However, when opening a directory from this share in Nautilus with Puddletag, the application freezes. This is also the case when dragging and dropping a directory to the app.

Currently using Puddletag 2.3.0

### Expected Behavior

Puddletag should respond and allow editing the files.

### Steps To Reproduce

See above

### Information about your system

Puddletag: 2.3.0
OS: Ubuntu 24.4
Installed with Flatpak 1.14.6

**Comment by sandrotosi** [comment]
We do not maintain the flatpak packaging of puddletag, so you should probably contact its maintainer directly.

If you want to try and install puddletag in ways we support, please follow any of [these methods|https://github.com/puddletag/puddletag/blob/master/README.md#how-to-install] and reopen this issue with additional information

thanks for using puddletag
