### ISSUE TITLE
Puddletag icon does not appear in "start" menu or taskbar on Linux

### ISSUE THREAD

**Issue by bassmadrigal** [puddletag/puddletag#914]
### Current Behavior

I'm the packager of puddletag for the Slackware Linux distribution. I'm not sure if this is something unique with my system, or something that's seen with other systems.

When installing the program, the puddletag.desktop file gets placed in /usr/share/applications/ and the puddletag.png gets placed in /usr/share/pixmaps/, and upon installation, `update-desktop-database` is ran against /usr/share/applications/. However, in the start menu and on the taskbar when ran, no icon is visible.

### Expected Behavior

Puddletag to show the icon in the start menu and taskbar without modifying the .desktop.

### Steps To Reproduce

Install via setup.py using [puddletag.SlackBuild](https://slackbuilds.org/slackbuilds/15.0/audio/puddletag/puddletag.SlackBuild) (bash build script).

### Information about your system

Puddletag: 2.4.0
OS: Slackware 15.0
Python: 3.9.19
PyQt: 5.15.2

### Anything else?

I was able to correct this issue on my system by specifying the /usr/share/pixmaps/puddletag (with or without the extension) in the puddletag.desktop file.

**Comment by sandrotosi** [comment]
im wondering if this is something more related to how slackware is handling images via desktop files than how puddletag definite its desktop file.

did you try to reach out to any support channels for slackware about this?

**Comment by bassmadrigal** [comment]
Thanks for your patience. I've had a busy week.

I've tried this on a few other Slackware systems and they all used the correct icon without needing adjustment to the .desktop. After realizing this, I reset the .desktop and reloaded my DE (Plasma 5) and it now works fine. 

Looks like it was a gremlin that a reboot would've also fixed, I'm just not used to needing to do that on Linux, so it never crossed my mind.

Sorry for the noise and thanks for the effort!
