### ISSUE TITLE
Version 2.4.0 wont start

### ISSUE THREAD

**Issue by Perkolator** [puddletag/puddletag#917]
### Current Behavior

Version 2.4.0 wont start. Version 2.3.0 works.

Starting from terminal:

```
$ ./puddletag

Traceback (most recent call last):
  File "./puddletag", line 341, in <module>
    migrate_settings()
  File "./puddletag", line 91, in migrate_settings
    _migrate_action_shortcuts()
  File "./puddletag", line 98, in _migrate_action_shortcuts
    from puddlestuff.puddleobjects import PuddleConfig
  File "/home/user/Programs/Puddletag/puddlestuff/puddleobjects.py", line 810, in <module>
    def progress(func: Callable[..., Generator[Optional[Tuple[str, int]], None, None]],
TypeError: 'ABCMeta' object is not subscriptable
```

### Expected Behavior

Would start.

### Steps To Reproduce

1. Try to start.

### Information about your system

Puddletag: 2.4.0
OS: Linux Mint 20.3 Cinnamon
Python: 3.8.10
PyQt: 5.14.1+dfsg-3build1

**Comment by Perkolator** [comment]
Not fixed. Other error comes now after testing both `from __future__ import annotations` or fix in #918.

```
puddletag Version: 2.4.0
qt5ct: using qt5ct plugin
Locale: en_US
Traceback (most recent call last):
  File "./puddletag", line 352, in <module>
    from puddlestuff.puddletag import MainWin
  File "/home/user/Programs/Puddletag/puddlestuff/puddletag.py", line 13, in <module>
    from . import m3u, genres
  File "/home/user/Programs/Puddletag/puddlestuff/m3u.py", line 11, in <module>
    from .findfunc import tagtofilename
  File "/home/user/Programs/Puddletag/puddlestuff/findfunc.py", line 11, in <module>
    from pyparsing import (CharsNotIn, Combine, Literal, OneOrMore, Optional, ParserElement,
ImportError: cannot import name 'delimited_list' from 'pyparsing' (/usr/lib/python3/dist-packages/pyparsing.py)
```

**Comment by Perkolator** [comment]
> Because you are using the distro-shipped v2.4 of pyparsing, the new PEP-8 names are only available since v3. Use a venv and it will work.

Whoosh. I have no idea of what you said. Except that puddletag 2.4.0 won't work on my OS anymore?

**Comment by Perkolator** [comment]
Like I already edited before, maybe you're too limiting who could easily use the new versions? Any idea given to Flatpak, or Appimage? Would those work with puddletag? That way lots of users would be easily allowed to use your newest versions, right?

**Comment by Perkolator** [comment]
> community-maintained FlatPak

3rd party is always a risk. And Flathub pages have started to mark such Flatpaks with yellow "Unverified" banner, and IIRC, the upcoming Mint package manager won't show such Flatpaks by default anymore.

Maybe you could make them your official Flatpak distributors? I vaguely remember that there are such situations with some software already. In case you don't want to do it yourself (I was under the impression that it would be somewhat easy to set up, and then mostly automatically update it.. but yeah, more work is more work, I can't deny that).

> you just have to account for the fact that your Linux has aged a tad

True true (I have plans to upgrade to the upcoming new major Mint release, skipped the previous one since I have lots of customizations and didn't have time to test them), however, I see that this problem happens with ubuntu 22.04 based distros as well (which is not that old), so I'd be in the same situation with the very latest Mint also.

Anyways, thanks for helping out, and thanks of course for puddletag. Think about making the 3rd party Flatpak official?

**Comment by domdfcoding** [comment]
Am I right that, as it stands, the package on PyPI which claims in its metadata to support "Python >=3.7" doesn't actually work on anything older than 3.9, but hasn't for whatever reason been yanked and replaced by a version with the correct metadata? Could it be yanked sometime as it's pointless being on PyPI with incorrect metadata that automated tools (pip) consume and install incompatible versions. If 2.4.0 was yanked pip would install 2.3.0 and everything works. A future 2.4.0.post1 with correct metadata will only be installed on the versions of Python it actually works on.
